name: Upload Asset - Linux

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    
jobs:
  build:
    name: Upload Asset - Linux
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # Might want debug once release works
        configuration: ['release'] # , 'debug']
        platform: ['x86', 'x64']
        
    steps:   
      - uses: actions/checkout@v2.3.4
        with:
          submodules: 'true'
          fetch-depth: '0'

      - name: premake
        run: |
          PREMAKE=external/slang-binaries/premake/premake-5.0.0-alpha16/bin/linux-64/premake5
          chmod u+x ${PREMAKE}
          ${PREMAKE} gmake --deps=true --no-progress=true          

      - name: Build
        run: |
          make config=${{matrix.configuration}}_${{matrix.platform}} verbose=1 -j`nproc`
          
      - name: archive
        id: archive
        run: |
          echo "achiving files..."
          
          ARCH_NAME=`uname -p`
          PLATFORM_NAME="linux-${{matrix.platform}}"
          TAG_NAME=`git describe --tags`
          SLANG_GLSLANG_VERSION=${TAG_NAME#"v"}
          
          echo "tag:$TAG_NAME"
          echo "slang-glslang-version:$GLSLANG_VERSION"
          
          BIN_ARCHIVE="slang-glslang-$TAG_NAME-$PLATFORM_NAME-${{matrix.configuration}}.zip"

          zip "$BIN_ARCHIVE" README.md
          zip "$BIN_ARCHIVE" LICENSE
          zip "$BIN_ARCHIVE" -r bin/*/*/*.so
          
          echo "name=BINARY_ARCHIVE::$BIN_ARCHIVE"
          echo "::set-output name=BINARY_ARCHIVE::$BIN_ARCHIVE"

      - name: Upload Archive
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.archive.outputs.BINARY_ARCHIVE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}