name: Upload Asset - MacOS

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    
jobs:
  build:
    name: Upload Asset - MacOS
    runs-on: macos-latest
    
    strategy:
      matrix:
        configuration: ['release'] # , 'debug']
        platform: ['x64']

    steps:   
      - uses: actions/checkout@v2.3.4
        with:
          submodules: 'true'
          fetch-depth: '0'
          # Build from the tag that triggered the build
          ref: ${{github.ref_name}}

      - name: premake
        run: |
          PREMAKE=external/slang-binaries/premake/premake-5.0.0-alpha16/bin/osx/premake5
          chmod u+x ${PREMAKE}
          ${PREMAKE} gmake --deps=true --no-progress=true          

      - name: Build
        run: |
          make config=${{matrix.configuration}}_${{matrix.platform}} -j`sysctl -n hw.ncpu`
          
      - name: archive
        id: archive
        run: |
          echo "achiving files..."

          PLATFORM="${{matrix.platform}}"
          
          if [[ "${PLATFORM}" == "x64" ]]; then
            PLATFORM="x86_64"
          fi
          
          ARCH_NAME=`uname -p`
          TAG_NAME=`git describe --tags`
          GLSLANG_VERSION=${TAG_NAME#"v"}
          
          echo "tag:$TAG_NAME"
          echo "glslang-version:$GLSLANG_VERSION"
          
          BIN_ARCHIVE="slang-glslang-$GLSLANG_VERSION-macosx-${PLATFORM}-${{matrix.configuration}}.zip"

          zip "$BIN_ARCHIVE" README.md
          zip "$BIN_ARCHIVE" LICENSE
          zip "$BIN_ARCHIVE" -r bin/*/*/*.dylib
          
          echo "name=BINARY_ARCHIVE::$BIN_ARCHIVE"
          echo "::set-output name=BINARY_ARCHIVE::$BIN_ARCHIVE"

      - name: Upload Archive
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.archive.outputs.BINARY_ARCHIVE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
